### ISSUE TITLE
more client drivers?

### ISSUE THREAD

**Issue by di3663** [namreg/godown#4]

**Comment by namreg** [comment]
@di3663 Hey!
I plan to add a php client. Feel free to add the one for your favorite language :)

**Comment by fangpianqi** [comment]
I hope you can add a java client, thanks to the author.

**Comment by namreg** [comment]
@di3663 @fangpianqi 
Hi! 
Since [1.2.0](https://github.com/namreg/godown/releases/tag/1.2.0) release godown supports redis protocol. Hence, you can connect to the one via any redis client.
